name: Update image_list1.json

on:
  push:
    paths:
      - 'img/**'

permissions:
  contents: write  # ✅ 允许 GitHub Actions 写入仓库

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate image_list.json (sorted by filename)
        run: |
          echo "🔍 读取 img/ 下所有图片..."
          node -e "
            const fs = require('fs');
            const path = require('path');
            const dir = 'img';
            const files = fs.readdirSync(dir)
              .filter(f => /\.(jpe?g|png)$/i.test(f))
              .sort(); // 按文件名排序
            console.log('✅ 获取到文件:', files);
            fs.writeFileSync(path.join(dir, 'image_list.json'), JSON.stringify(files, null, 2));
          "

      - name: Commit and push updated image_list.json
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add img/image_list.json
          git commit -m "🤖 Auto update image_list.json" || echo "✅ 无需提交"
          git push
