name: Update image_list.json

on:
  push:
    paths:
      - 'img/**'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate image_list.json
        run: |
          node -e "
            const fs = require('fs');
            const path = require('path');
            const dir = 'img';
            const files = fs.readdirSync(dir)
              .filter(f => /\.(jpg|jpeg|png)$/i.test(f))
              .sort();
            fs.writeFileSync(path.join(dir, 'image_list.json'), JSON.stringify(files, null, 2));
          "

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add img/image_list.json
          git commit -m "🤖 Auto update image_list.json"
          git push
